#!/bin/sh
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
sudo apt-get install vim
vim +PluginInstall +qall

sudo apt-get install tmux
sudo apt-get install silversearcher-ag
